FRASES = [
    "Brincar é a forma mais natural de aprender.",
    "Cada brinquedo pode despertar uma nova descoberta.",
    "Cultivar a infância é investir no futuro.",
    "Pequenas mãos constroem grandes sonhos.",
    "Primeiro iniciamos, depois melhoramos.",
    "A constância transforma desafios em resultados.",
    "Toda brincadeira carrega uma oportunidade de aprender.",
    "O desenvolvimento acontece uma descoberta de cada vez.",
    "Aprender pode ser tão divertido quanto brincar.",
    "A infância floresce quando há espaço para explorar.",
    "Cada criança aprende no seu próprio tempo.",
    "Grandes aprendizados começam com pequenas curiosidades.",
    "Brincar hoje é construir o amanhã.",
    "A imaginação é o primeiro passo para criar.",
    "O futuro nasce das experiências da infância.",
    "Valorizar a infância é transformar gerações.",
    "Toda criança merece tempo para brincar e descobrir.",
    "Brinquedos simples despertam aprendizagens profundas.",
    "A curiosidade é a semente do conhecimento.",
    "Cada descoberta fortalece a confiança para crescer.",
    "O brincar desenvolve habilidades para a vida inteira.",
    "A criatividade cresce quando a imaginação encontra espaço.",
    "Aprender brincando torna a jornada mais significativa.",
    "Pequenos gestos criam grandes memórias.",
    "A infância é o terreno onde os sonhos começam.",
    "Brincar também é uma forma de aprender sobre o mundo.",
    "Toda conquista começou com uma tentativa.",
    "O crescimento acontece um passo de cada vez.",
    "Persistir é continuar mesmo quando o resultado ainda não apareceu.",
    "A evolução diária supera a perfeição imediata.",
    "O aprendizado é construído na prática.",
    "A dedicação de hoje constrói os resultados de amanhã.",
    "Toda melhoria começa com uma decisão.",
    "Planejar é transformar sonhos em possibilidades.",
    "Organização gera tranquilidade para crescer.",
    "O sucesso é consequência da constância.",
    "Pequenos avanços também merecem ser celebrados.",
    "A excelência nasce dos detalhes.",
    "Quem aprende todos os dias evolui todos os dias.",
    "Grandes resultados são feitos de pequenas ações repetidas.",
    "A natureza ensina que todo crescimento leva tempo.",
    "Respeitar o tempo da infância é respeitar o desenvolvimento.",
    "Assim como uma árvore cresce aos poucos, o aprendizado também.",
    "Cuidar do planeta é cuidar das futuras gerações.",
    "Escolhas conscientes geram impactos duradouros.",
    "Sustentabilidade é pensar no amanhã sem esquecer o hoje.",
    "Brinquedos que inspiram, aprendizados que permanecem.",
    "Cada dia traz uma nova oportunidade de evoluir.",
    "A jornada é tão importante quanto o destino.",
    "O melhor momento para começar é agora.",
    "Aprender, brincar e crescer fazem parte da mesma jornada.",
    "Toda criança carrega um potencial extraordinário.",
    "O conhecimento floresce onde existe curiosidade.",
    "O brincar livre desperta criatividade e autonomia.",
    "Quando a criança explora, o aprendizado acontece naturalmente.",
    "Construindo experiências que inspiram descobertas.",
    "O futuro é construído pelas pequenas ações de hoje.",
    "A infância merece ser vivida com significado.",
    "A alegria de brincar também ensina.",
    "Cada dia é uma nova chance para fazer melhor."
]